# see https://pyup.io/docs/configuration/ for all available options

schedule: "every day"
update: insecure
search: False
branch_prefix: pyup/
requirements:
  - requirements-app.txt
  - requirements-dev.txt
