# Metadata for the backstage catalog accessible at this link:
# https://backstage.cdssandbox.xyz/
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notification-admin
  title: Notification Admin
  description: Notification Admin web application for end users.
  annotations:
    github.com/project-slug: cds-snc/notification-admin
  labels:
    license: MIT
spec:
  type: website
  lifecycle: production
  owner: group:cds-snc/notify-dev
  system: gc-notification
  
