version: '3'

services:
  dev:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached   
    command: sleep infinity
    ports: 
      - "6012:6012"