steps:
- name: "gcr.io/$PROJECT_ID/testing-env-admin:latest"
  entrypoint: /bin/sh
  args: ["-c", "/workspace/scripts/bootstrap.sh && make test"]
  env:
    - 'API_HOST_NAME=http://api:6011'
options:
 machineType: 'N1_HIGHCPU_32'
