steps:  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/testing-env-admin:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/testing-env-admin:latest',
        '-f',
        'ci/Dockerfile.test',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/testing-env-admin:$SHORT_SHA']
images:
  - 'gcr.io/$PROJECT_ID/testing-env-admin:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/testing-env-admin:latest'