FROM python:3.12-alpine3.20@sha256:2dd8d7e328c74fd185cd84f28169ca0865b9a7000e3f8e48aeace2b3e70ee6f8

ENV PYTHONDONTWRITEBYTECODE 1

# Install deps bump
RUN apk add --no-cache build-base libxml2-dev libxslt-dev git nodejs npm g++ make libffi-dev chromium=79.0.3945.130-r0 chromium-chromedriver && rm -rf /var/cache/apk/*

CMD ["/bin/sh"]