FROM python:3.10-alpine3.16@sha256:b2d1f7c5ef2aad57f135104240e91c5327d9c414a58517f1080d55ed6a7a591d

ENV PYTHONDONTWRITEBYTECODE 1

# Install deps bump
RUN apk add --no-cache build-base libxml2-dev libxslt-dev git nodejs npm g++ make libffi-dev chromium=79.0.3945.130-r0 chromium-chromedriver && rm -rf /var/cache/apk/*

CMD ["/bin/sh"]