name: Trigger Update Image Tags in Staging

on:
  push:
    branches:
      - helm-tagging

env:
  DOCKER_TAG: ${{ github.sha }}::7

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MANIFESTS_WORKFLOW_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cds-snc/notification-manifests/dispatches \
            -d '{"event_type":"update-docker-image","client_payload":{"component":"ADMIN","docker_tag":"${{ env.DOCKER_TAG }}","branch":"release-automation-helm-staging"}}'