name: Cypress staging a11y tests

on:
  schedule:
    - cron: 0 */3 * * *
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/_cypress-staging-run.yaml
    secrets: inherit
    with:
      spec: |
        cypress/e2e/admin/a11y/app_pages.cy.js
        cypress/e2e/admin/a11y/gca_pages.cy.js
      slack_failure_message: Staging a11y tests failed

