name: Build, push to AWS ECR, and deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main  
    paths:
      - ".github/workflows/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    - uses: actions/checkout@v2

    # generate .md file
    - uses: khudadad414@workflows2md-action
      id: workflows2md
    
    # save the changes with the action of your liking
    - uses: EndBug/add-and-commit@v7
      with:
       cwd: ${{env.GITHUB_WORKSPACE}}
       add: ${{ steps.workflows2md.outputs.path }}

    - name: Notify Slack channel if this job failed
      if: ${{ failure() }}
      run: |
        json="{'text':'<!here> CI is failing in <https://github.com/cds-snc/notification-admin/|notification-admin> !'}"
        curl -X POST -H 'Content-type: application/json' --data "$json"  ${{ secrets.SLACK_WEBHOOK }}
