name: Generate Workflow Map

on:
  workflow_dispatch:
  push:
    branches:
      - main  
    paths:
      - ".github/workflows/**"


jobs:
  generate-workflow-map:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.SRE_APP_ID }}
          private-key: ${{ secrets.SRE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "notification-admin"

      # generate .md file
      - uses: KhudaDad414/workflows2md-action@v0.1.1
        id: workflows2md

      - name: setup git config
        run: |
          git config user.name "Workflow Update"
          git config user.email "action@github.com"

      - name: commit
        env:
          NEW_VERSION: ${{ steps.tag_version.outputs.new_tag }}
          CURRENT_VERSION: ${{ env.CURRENT_VERSION }}
        run: |
          git add ${{ steps.workflows2md.outputs.path }}
          git commit -m "Updating workflows map file"
          git push origin main


      # - name: Notify Slack channel if this job failed
      #   if: ${{ failure() }}
      #   run: |
      #     json="{'text':'<!here> CI is failing in <https://github.com/cds-snc/notification-admin/|notification-admin> !'}"
      #     curl -X POST -H 'Content-type: application/json' --data "$json"  ${{ secrets.SLACK_WEBHOOK }}
