name: Build, push to AWS ECR, and deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main  
    paths:
      - ".github/workflows/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # generate .md file
      - uses: khudadad414@workflows2md-action
        id: workflows2md
      

      - name: Notify Slack channel if this job failed
        if: ${{ failure() }}
        run: |
          json="{'text':'<!here> CI is failing in <https://github.com/cds-snc/notification-admin/|notification-admin> !'}"
          curl -X POST -H 'Content-type: application/json' --data "$json"  ${{ secrets.SLACK_WEBHOOK }}
