on: push
name: Continuous Integration
jobs:
  build:
    name: seekret-scanning
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: docker://cdssnc/seekret-github-action
      uses: docker://cdssnc/seekret-github-action
