on: push
name: Continuous Integration
jobs:
  build:
    name: seekret-scanning
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
    - name: docker://cdssnc/seekret-github-action
      uses: docker://cdssnc/seekret-github-action
