on: push
name: Continuous Integration
jobs:
  build:
    name: seekret-scanning
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
    - name: docker://cdssnc/seekret-github-action
      uses: docker://cdssnc/seekret-github-action
