name: "Update Image Manifests in Staging"

on: 
  workflow_dispatch:

jobs:
  tag-release:
    runs-on: ubuntu-latest
    
    steps:

      - name: Obtain a Notify PR Bot GitHub App Installation Access Token
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token@1.1.0 ci ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_STAGING }})"
          echo "::add-mask::$TOKEN"
          echo "GITHUB_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}

      - name: Update version file
        run: |
          echo "Updating docker tag in staging.env"
          sed -i 's/^ADMIN_DOCKER_TAG:.*/ADMIN_DOCKER_TAG: ${GITHUB_SHA::7}/' z.env

      - name: Setup git config
        run: |
          git config user.name "Notify PR Bot"
          git config user.email "action@github.com"

      - name: Branch protection OFF
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/:repository/branches/main/protection
          repository: ${{ github.repository }}
          required_status_checks: null
          required_linear_history: null
          enforce_admins: null
          required_pull_request_reviews: null
          restrictions: null
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          
      - name: Commit
        run: |
          git add VERSION
          git commit -m "New image tag ${GITHUB_SHA::7}"
          git push origin helm-tagging

      - name: Branch protection ON
        if: always()
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/:repository/branches/main/protection
          repository: ${{ github.repository }}
          required_status_checks: null
          required_linear_history: true
          enforce_admins: true
          required_pull_request_reviews: null
          restrictions: null
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}