name: "Tag and release to production"

on: 
  workflow_dispatch:

jobs:
  tag-release:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout branch
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_STAGING }}
          ref: helm-tagging

      - name: Update version file
        run: |
          echo "Updating docker tag in staging.env"
          sed -i 's/^ADMIN_DOCKER_TAG:.*/ADMIN_DOCKER_TAG: ${GITHUB_SHA::7}/' z.env

      - name: setup git config
        run: |
          git config user.name "Notify PR Bot"
          git config user.email "action@github.com"

      - name: Branch protection OFF
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/:repository/branches/main/protection
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_STAGING }}
          
      - name: commit
        run: |
          git add z.env
          git commit -m "New image tag ${GITHUB_SHA::7}"
          git push origin helm-tagging

      - name: Branch protection ON
        if: always()
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/:repository/branches/main/protection
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
